pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    pull: true
    restore: true
    mount:
    - ./cache
    volumes:
    - /cache:/cache
  test:
    image: python:3.6-slim-jessie
    pull: true
    commands:
    - python3 -V
    - pip3 -V
    - pip3 install -r requirements/test.txt
    - python3 -m unittest discover -s tests
    - bash build.sh
    environment:
    - XDG_CACHE_HOME=./cache
    - FLASK_ENV=test
    when:
      event: push
  publish:
    image: plugins/docker
    pull: true
    repo: datashaman/wifidog-auth-flask
    tags: ${DRONE_COMMIT_BRANCH/master/latest}
    when:
      event: push
    secrets:
    - docker_password
    - docker_username
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
    - ./cache
    volumes:
    - /cache:/cache
  notify:
    image: plugins/slack
    pull: true
    channel: ci
    when:
      status: [ success, failure ]
    secrets:
    - slack_webhook
