matrix:
  PYTHON_VERSION:
  - 2.7
  - 3.6

cache:
- /root/.cache

pipeline:
  test:
    image: python:${PYTHON_VERSION}-slim-jessie
    commands:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests
    environment:
    - TESTING=true
    when:
      event: push
  publish:
    image: plugins/docker
    repo: datashaman/wifidog-auth-flask
    tags: ${DRONE_COMMIT_BRANCH/master/latest}
    when:
      event: push
      matrix:
        PYTHON_VERSION: 3.6
    secrets: [ docker_username, docker_password ]
  notify:
    image: plugins/slack
    channel: ci
    when:
      status: [ success, failure ]
    secrets: [ slack_webhook ]
