matrix:
  PYTHON_VERSION:
  - 2.7
  - 3.6

cache:
- /root/.cache

pipeline:
  pre_deploy:
    image: python:${PYTHON_VERSION}-slim-jessie
    commands:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests
    environment:
    - TESTING=true
    when:
      event: push
  deploy:
    image: python:2.7-slim-jessie
    commands:
    - bash deploy.sh ${DRONE_COMMIT_BRANCH}
    secrets: [ deploy_key ]
    when:
      event: push
      branch: master
      matrix:
        PYTHON_VERSION: 3.6
  notify:
    image: plugins/slack
    channel: ci
    when:
      status: [ success, failure ]
    secrets: [ slack_webhook ]
